[pathing]
outer_dir_name = "TidalPy-Run"
append_datetime = true

[debug]
extensive_logging = true

[logging]
use_cwd = true
write_log = true
console_level = "DEBUG"
console_error_level = "WARNING"
file_level = "WARNING"
print_log_notebook = false
write_log_notebook = false

[configs]
save_configs_locally = true
