dist: xenial

language: python

os:
  - linux
  - osx
  - windows

python:
  - "3.7"
  - "3.8"

# command to install dependencies

install:
  - pip install -e .

# command to run tests
script:
  - pytest