name: tidalpy_env
channels:
dependencies:
  - setuptools>=57.0.0
  - pip>=21.0.0
  - wheel>=0.36.0
  - dill>=0.3.2
  - ipympl>=0.7.0
  - ipython>=7.24.1
  - ipywidgets>=7.6.3
  - json5>=0.9.5
  - jupyter>=1.0
  - matplotlib>=3.4.2
  - numba>=0.53
  - numpy>=1.19.5,<1.20.0
  - pytest>=6.2.4
  - scipy>=1.6.3
  - pandas>=1.2.4
  - pip:
    - "git+https://github.com/geodynamics/burnman.git"
    - pathos
    - .