name: tidalpy_env
channels:
dependencies:
  - setuptools>=51.0.0
  - pip>=20.2.2
  - dill>=0.3.2
  - ipympl>=0.5.8
  - ipython>=7.19.0
  - ipywidgets>=7.6.3
  - json5>=0.9.5
  - jupyter>=1.0
  - matplotlib>=3.3.2
  - numba>=0.51.2
  - numpy>=1.19.2
  - pytest>=6.0.1
  - scipy>=1.5.2
  - pip:
    - "git+https://github.com/geodynamics/burnman.git"
    - pathos
    - .