name: tidalpy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - setuptools>=57.0.0
  - pip>=21.0.0
  - wheel>=0.36.0
  - pytest>=6.2.4
  - pytest-cov>=3.0.0
  - coverage>=6.3
  - numpy>=1.19.5
  - pandas>=1.2.4
  - matplotlib>=3.4.2
  - scipy>=1.6.3
  - numba>=0.53
  - pytest>=6.2.4
  - pytest-split>=0.7.0
  - ipympl>=0.7.0
  - ipython>=7.24.1
  - ipywidgets>=7.6.3
  - jupyter>=1.0
  - json5>=0.9.5
  - dill>=0.3.2
  - psutil>=5.8.0
  - pathos>=0.2.0
  - ecos>=2.0.8
  - scs>=3.0.0
  - proj>=8.0.0
  - geos>=3.7.2
  - cartopy>=0.18.0
  - pip:
    - pycddlib>=2.1
    - burnman>=1.0.1
    - .
