{% set name = "TidalPy" %}
{% set version = "0.8.0a1.dev2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tidalpy-{{ version }}.tar.gz
  # Replace with the sha256 of the version's sdist on PyPI.
  sha256: e50d8af5186a566beeffbab764a9148159b5eed08b4d1391377ab5a63aad4de4

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - cython
    - wheel
    - cyrk >=0.19.0,<0.20.0
    - pip
  run:
    - python
    - numba
    - numpy
    - scipy
    - platformdirs
    - toml
    - dill
    - psutil
    - pathos
    - cyrk >=0.19.0,<0.20.0
    - astropy-base
    - astroquery
    - matplotlib-base >=3.4.2

test:
  imports:
    - TidalPy
  commands:
    - python -c "import TidalPy; from TidalPy.RadialSolver import radial_solver; from TidalPy.structures import build_world; print(TidalPy.__version__)"
    - pip check
  requires:
    - pip

about:
  home: www.tidalpy.info/
  summary: Tidal Dynamics and Thermal-Orbital Evolution Software Suite Implemented in Cython and Python
  description: |
    TidalPy provides efficient tools to estimate tidal dissipation within rocky and icy worlds.
    The RaidalSolver package includes tools to calculate a planet or moon's "Love" numbers.
    The Tides package includes tools to estimate tidal heating and spin-orbit evolution including the effects from
    higher-order eccentricity and obliquity terms which are often left out of other models. 
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://github.com/jrenaud90/TidalPy/tree/main/Documentation
  dev_url: https://github.com/jrenaud90/TidalPy

extra:
  recipe-maintainers:
    - jrenaud90
