from TidalPy.Tides_x.mode_func_common cimport c_ModeFuncOutput
from TidalPy.Tides_x.obliquity.obliquity_common cimport c_ObliquitySeriesTable, c_ObliquityGeneralTable
from TidalPy.Tides_x.obliquity.obliquity_func_l2 cimport c_obliquity_series_l2, c_obliquity_general_l2
from TidalPy.Tides_x.obliquity.obliquity_func_l3 cimport c_obliquity_series_l3, c_obliquity_general_l3
from TidalPy.Tides_x.obliquity.obliquity_func_l4 cimport c_obliquity_series_l4, c_obliquity_general_l4
from TidalPy.Tides_x.obliquity.obliquity_func_l5 cimport c_obliquity_series_l5, c_obliquity_general_l5
from TidalPy.Tides_x.obliquity.obliquity_func_l6 cimport c_obliquity_series_l6, c_obliquity_general_l6
from TidalPy.Tides_x.obliquity.obliquity_func_l7 cimport c_obliquity_series_l7, c_obliquity_general_l7
from TidalPy.Tides_x.obliquity.obliquity_func_l8 cimport c_obliquity_series_l8, c_obliquity_general_l8
from TidalPy.Tides_x.obliquity.obliquity_func_l9 cimport c_obliquity_series_l9, c_obliquity_general_l9
from TidalPy.Tides_x.obliquity.obliquity_func_l10 cimport c_obliquity_series_l10, c_obliquity_general_l10

from TidalPy.Tides_x.obliquity.obliquity_driver cimport (
    c_obliquity_series_table, c_obliquity_general_table, c_obliquity_func, c_obliquity_squared_func)
