#pragma once
/*
 * obliquity_common_.hpp - the obliquity-function table format and its evaluation.
 *
 * The obliquity (inclination) functions F_lmp(I) are Kaula's (1964), in the half-angle form of Gooding and Wagner
 * (2008). Truncation level N (0, 2, or 4) is defined by the heating, as for the eccentricity functions: every product
 * of two obliquity functions is kept through I^N and nothing past it. A level's table holds every function whose
 * Taylor series starts at or below I^N, each through I^N,
 *
 *   F_lmp(I) = I^lead * sum_j c_j I^(2j),   lead = |l - m - 2p|,   lead + 2j <= N,
 *
 * so the unsquared functions, and a tidal potential built from them, are complete through I^N. Products are formed and
 * cut at I^N here (c_obliquity_cut_product), which is why a function enters the heating only when lead <= N / 2.
 * Level 0 is F at I = 0 (the obliquity off). The general truncation (C_OBLIQUITY_GENERAL) evaluates the half-angle sum
 *
 *   F_lmp(I) = sum_k a_k cos(I/2)^(alpha_k) sin(I/2)^(beta_k),
 *
 * exact at any obliquity, and its products are plain products.
 *
 * The tables (obliquity_func_l{l}_.hpp) are generated by cpp_obliquity_func_builder.py in the derivations repository
 * with exact rational arithmetic. Each is dense in (m, p): entry m * (l + 1) + p is function (m, p), and a function
 * that vanishes identically, or that starts past I^N, has no coefficients.
 */

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <vector>

#include "../mode_func_common_.hpp"               // c_ModeFuncOutput
#include "../../Utilities_x/math_x/series_.hpp"   // Horner sums, powers, cut Cauchy products
#include "obliquity_accuracy_.hpp"                // C_OBLIQUITY_OFF, C_OBLIQUITY_GENERAL

// The tabulated truncation levels, the one list every entry point validates against (C_OBLIQUITY_GENERAL aside).
inline constexpr int C_OBLIQUITY_TRUNCATIONS[] = {0, 2, 4};
inline constexpr int C_NUM_OBLIQUITY_TRUNCATIONS =
    static_cast<int>(sizeof(C_OBLIQUITY_TRUNCATIONS) / sizeof(C_OBLIQUITY_TRUNCATIONS[0]));

// One function of a table: its coefficients (or half-angle terms) in the table's array.
struct c_ObliquityModeSeries {
    int32_t offset;   // index of the first coefficient or term
    int16_t count;    // number of coefficients or terms; 0 for a function that vanishes or starts past I^N
};

// One (degree, truncation) series table. modes is null for an untabulated level.
struct c_ObliquitySeriesTable {
    int degree_l = 0;
    int truncation = 0;
    const c_ObliquityModeSeries* modes = nullptr;
    const double* coefficients = nullptr;

    bool valid() const noexcept { return this->modes != nullptr; }

    // Function (m, p) for 0 <= m, p <= l.
    const c_ObliquityModeSeries& mode(int m, int p) const noexcept {
        return this->modes[m * (this->degree_l + 1) + p];
    }
};

// One term a cos(I/2)^cos_power sin(I/2)^sin_power of the half-angle sum.
struct c_ObliquityHalfAngleTerm {
    double coefficient;
    int16_t cos_power;
    int16_t sin_power;
};

// The general (half-angle) table of one degree.
struct c_ObliquityGeneralTable {
    int degree_l = 0;
    const c_ObliquityModeSeries* modes = nullptr;
    const c_ObliquityHalfAngleTerm* terms = nullptr;

    bool valid() const noexcept { return this->modes != nullptr; }

    const c_ObliquityModeSeries& mode(int m, int p) const noexcept {
        return this->modes[m * (this->degree_l + 1) + p];
    }
};

// F_lmp of one degree, or its cut square, over 0 <= m, p <= l; zero for every function left out. table is the
// (degree, truncation) table the values came from, for the cut products of two of them, and invalid for the general
// functions.
struct c_ObliquityValues {
    int degree_l = 0;
    std::vector<double> values;   // [m * (l + 1) + p]
    c_ObliquitySeriesTable table;

    double value(int order_m, int p) const noexcept {
        return this->values[static_cast<size_t>(order_m * (this->degree_l + 1) + p)];
    }
};

// The lead power of F_lmp's Taylor series.
inline int c_obliquity_lead_power(int degree_l, int order_m, int p) noexcept {
    return std::abs(degree_l - order_m - 2 * p);
}

// F_lmp(I) through I^N.
inline double c_obliquity_mode_value(const c_ObliquitySeriesTable& table, int order_m, int p, double obliquity)
        noexcept {
    const c_ObliquityModeSeries& mode = table.mode(order_m, p);
    if (mode.count == 0) { return 0.0; }
    return c_series_power(obliquity, c_obliquity_lead_power(table.degree_l, order_m, p))
         * c_series_horner(table.coefficients + mode.offset, mode.count, obliquity * obliquity);
}

// The product F_a F_b cut at I^N, N the (common) truncation of the two tables. Zero when the product's leading power
// lead_a + lead_b is past I^N.
inline double c_obliquity_cut_product(
        const c_ObliquitySeriesTable& table_a,
        int order_m_a,
        int p_a,
        const c_ObliquitySeriesTable& table_b,
        int order_m_b,
        int p_b,
        double obliquity) noexcept {
    const int truncation = table_a.truncation;
    const int lead = c_obliquity_lead_power(table_a.degree_l, order_m_a, p_a)
                   + c_obliquity_lead_power(table_b.degree_l, order_m_b, p_b);
    if (lead > truncation) { return 0.0; }
    const c_ObliquityModeSeries& mode_a = table_a.mode(order_m_a, p_a);
    const c_ObliquityModeSeries& mode_b = table_b.mode(order_m_b, p_b);
    if ((mode_a.count == 0) || (mode_b.count == 0)) { return 0.0; }
    const double* coefficients_a = table_a.coefficients + mode_a.offset;
    const double* coefficients_b = table_b.coefficients + mode_b.offset;
    // Cauchy product of the two series, cut at I^(2 max_s) past the leading power, then Horner in I^2.
    const int max_s = (truncation - lead) / 2;
    const double obliquity_2 = obliquity * obliquity;
    const double total = c_series_cut_product(
        c_SeriesSpan{coefficients_a, mode_a.count}, c_SeriesSpan{coefficients_b, mode_b.count}, max_s, obliquity_2);
    return c_series_power(obliquity, lead) * total;
}

// The half-angle powers the general functions of one degree need: cos(I/2)^k and sin(I/2)^k for 0 <= k <= 3l.
struct c_ObliquityHalfAnglePowers {
    static constexpr int max_power = 30;   // 3 l at l = 10
    double cos_powers[max_power + 1];
    double sin_powers[max_power + 1];

    explicit c_ObliquityHalfAnglePowers(double obliquity) noexcept {
        const double cos_half = std::cos(0.5 * obliquity);
        const double sin_half = std::sin(0.5 * obliquity);
        this->cos_powers[0] = 1.0;
        this->sin_powers[0] = 1.0;
        for (int k = 1; k <= max_power; ++k) {
            this->cos_powers[k] = this->cos_powers[k - 1] * cos_half;
            this->sin_powers[k] = this->sin_powers[k - 1] * sin_half;
        }
    }
};

// The general F_lmp(I), exact.
inline double c_obliquity_general_value(
        const c_ObliquityGeneralTable& table, int order_m, int p, const c_ObliquityHalfAnglePowers& powers) noexcept {
    const c_ObliquityModeSeries& mode = table.mode(order_m, p);
    double total = 0.0;
    for (int k = 0; k < mode.count; ++k) {
        const c_ObliquityHalfAngleTerm& term = table.terms[mode.offset + k];
        total += term.coefficient * powers.cos_powers[term.cos_power] * powers.sin_powers[term.sin_power];
    }
    return total;
}
