#pragma once
// Obliquity-function tables for degree l = 5, generated by
// cpp_obliquity_func_builder.py (derivations repository). Do not edit by hand.

#include "obliquity_common_.hpp"

// Truncation 0: every F_lmp starting at or below I^0, each through I^0.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l5_i0[36] = {
    {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0},
    {0, 0}, {0, 0}, {0, 1}, {1, 0}, {1, 0}, {1, 0},
    {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0},
    {1, 0}, {1, 1}, {2, 0}, {2, 0}, {2, 0}, {2, 0},
    {2, 0}, {2, 0}, {2, 0}, {2, 0}, {2, 0}, {2, 0},
    {2, 1}, {3, 0}, {3, 0}, {3, 0}, {3, 0}, {3, 0},
};
inline constexpr double c_obliquity_coeffs_l5_i0[3] = {
    1.875, -52.5, 945.0,
};

// Truncation 2: every F_lmp starting at or below I^2, each through I^2.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l5_i2[36] = {
    {0, 0}, {0, 0}, {0, 1}, {1, 1}, {2, 0}, {2, 0},
    {2, 0}, {2, 1}, {3, 2}, {5, 1}, {6, 0}, {6, 0},
    {6, 0}, {6, 1}, {7, 1}, {8, 0}, {8, 0}, {8, 0},
    {8, 1}, {9, 2}, {11, 1}, {12, 0}, {12, 0}, {12, 0},
    {12, 1}, {13, 1}, {14, 0}, {14, 0}, {14, 0}, {14, 0},
    {14, 2}, {16, 1}, {17, 0}, {17, 0}, {17, 0}, {17, 0},
};
inline constexpr double c_obliquity_coeffs_l5_i2[17] = {
    0.9375, -0.9375, 6.5625, 1.875, -13.59375, 7.03125,
    -26.25, 26.25, -118.125, -52.5, 275.625, -157.5,
    472.5, -472.5, 945.0, -1181.25, 1181.25,
};

// Truncation 4: every F_lmp starting at or below I^4, each through I^4.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l5_i4[36] = {
    {0, 0}, {0, 1}, {1, 2}, {3, 2}, {5, 1}, {6, 0},
    {6, 1}, {7, 2}, {9, 3}, {12, 2}, {14, 1}, {15, 0},
    {15, 1}, {16, 2}, {18, 2}, {20, 1}, {21, 0}, {21, 0},
    {21, 2}, {23, 3}, {26, 2}, {28, 1}, {29, 0}, {29, 0},
    {29, 2}, {31, 2}, {33, 1}, {34, 0}, {34, 0}, {34, 0},
    {34, 3}, {37, 2}, {39, 1}, {40, 0}, {40, 0}, {40, 0},
};
inline constexpr double c_obliquity_coeffs_l5_i4[40] = {
    1.09375, 0.9375, -3.4375, -0.9375, 3.4375, -1.09375,
    2.4609375, 6.5625, -13.671875, 1.875, -13.59375, 24.1015625,
    7.03125, -16.9921875, 4.1015625, -19.6875, -26.25, 76.5625,
    26.25, -89.6875, 32.8125, -118.125, 127.96875, -52.5,
    275.625, -357.65625, -157.5, 328.125, -98.4375, 472.5,
    -551.25, -472.5, 1023.75, -472.5, 945.0, -1181.25,
    689.0625, 1181.25, -1279.6875, 590.625,
};

// General: the half-angle sum of every F_lmp, exact at any obliquity.
inline constexpr c_ObliquityModeSeries c_obliquity_general_modes_l5[36] = {
    {0, 1}, {1, 3}, {4, 5}, {9, 5}, {14, 3}, {17, 1},
    {18, 1}, {19, 3}, {22, 5}, {27, 5}, {32, 3}, {35, 1},
    {36, 1}, {37, 3}, {40, 4}, {44, 4}, {48, 3}, {51, 1},
    {52, 1}, {53, 3}, {56, 3}, {59, 3}, {62, 3}, {65, 1},
    {66, 1}, {67, 2}, {69, 2}, {71, 2}, {73, 2}, {75, 1},
    {76, 1}, {77, 1}, {78, 1}, {79, 1}, {80, 1}, {81, 1},
};
inline constexpr c_ObliquityHalfAngleTerm c_obliquity_general_terms_l5[82] = {
    {7.875, 5, 5}, {8.75, 7, 3}, {-21.875, 5, 5},
    {8.75, 3, 7}, {1.875, 9, 1}, {-18.75, 7, 3},
    {37.5, 5, 5}, {-18.75, 3, 7}, {1.875, 1, 9},
    {-1.875, 9, 1}, {18.75, 7, 3}, {-37.5, 5, 5},
    {18.75, 3, 7}, {-1.875, 1, 9}, {-8.75, 7, 3},
    {21.875, 5, 5}, {-8.75, 3, 7}, {-7.875, 5, 5},
    {39.375, 6, 4}, {26.25, 8, 2}, {-105.0, 6, 4},
    {65.625, 4, 6}, {1.875, 10, 0}, {-45.0, 8, 2},
    {168.75, 6, 4}, {-150.0, 4, 6}, {28.125, 2, 8},
    {28.125, 8, 2}, {-150.0, 6, 4}, {168.75, 4, 6},
    {-45.0, 2, 8}, {1.875, 0, 10}, {65.625, 6, 4},
    {-105.0, 4, 6}, {26.25, 2, 8}, {39.375, 4, 6},
    {-157.5, 7, 3}, {-52.5, 9, 1}, {367.5, 7, 3},
    {-367.5, 5, 5}, {52.5, 9, 1}, {-472.5, 7, 3},
    {787.5, 5, 5}, {-262.5, 3, 7}, {262.5, 7, 3},
    {-787.5, 5, 5}, {472.5, 3, 7}, {-52.5, 1, 9},
    {367.5, 5, 5}, {-367.5, 3, 7}, {52.5, 1, 9},
    {157.5, 3, 7}, {-472.5, 8, 2}, {-52.5, 10, 0},
    {840.0, 8, 2}, {-1470.0, 6, 4}, {-630.0, 8, 2},
    {2520.0, 6, 4}, {-1575.0, 4, 6}, {-1575.0, 6, 4},
    {2520.0, 4, 6}, {-630.0, 2, 8}, {-1470.0, 4, 6},
    {840.0, 2, 8}, {-52.5, 0, 10}, {-472.5, 2, 8},
    {945.0, 9, 1}, {-945.0, 9, 1}, {3780.0, 7, 3},
    {-3780.0, 7, 3}, {5670.0, 5, 5}, {-5670.0, 5, 5},
    {3780.0, 3, 7}, {-3780.0, 3, 7}, {945.0, 1, 9},
    {-945.0, 1, 9}, {945.0, 10, 0}, {4725.0, 8, 2},
    {9450.0, 6, 4}, {9450.0, 4, 6}, {4725.0, 2, 8},
    {945.0, 0, 10},
};

// The tables of one truncation level; a table with no modes for an untabulated level.
inline c_ObliquitySeriesTable c_obliquity_series_l5(int truncation) noexcept {
    switch (truncation) {
        case 0: return c_ObliquitySeriesTable{5, 0, c_obliquity_modes_l5_i0, c_obliquity_coeffs_l5_i0};
        case 2: return c_ObliquitySeriesTable{5, 2, c_obliquity_modes_l5_i2, c_obliquity_coeffs_l5_i2};
        case 4: return c_ObliquitySeriesTable{5, 4, c_obliquity_modes_l5_i4, c_obliquity_coeffs_l5_i4};
        default: return c_ObliquitySeriesTable{};
    }
}

// The half-angle table of the general truncation.
inline c_ObliquityGeneralTable c_obliquity_general_l5() noexcept {
    return c_ObliquityGeneralTable{5, c_obliquity_general_modes_l5, c_obliquity_general_terms_l5};
}
