#pragma once
// Obliquity-function tables for degree l = 2, generated by
// cpp_obliquity_func_builder.py (derivations repository). Do not edit by hand.

#include "obliquity_common_.hpp"

// Truncation 0: every F_lmp starting at or below I^0, each through I^0.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l2_i0[9] = {
    {0, 0}, {0, 1}, {1, 0}, {1, 0}, {1, 0}, {1, 0},
    {1, 1}, {2, 0}, {2, 0},
};
inline constexpr double c_obliquity_coeffs_l2_i0[2] = {
    -0.5, 3.0,
};

// Truncation 2: every F_lmp starting at or below I^2, each through I^2.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l2_i2[9] = {
    {0, 1}, {1, 2}, {3, 1}, {4, 1}, {5, 1}, {6, 0},
    {6, 2}, {8, 1}, {9, 0},
};
inline constexpr double c_obliquity_coeffs_l2_i2[9] = {
    -0.375, -0.5, 0.75, -0.375, 1.5, -1.5,
    3.0, -1.5, 1.5,
};

// Truncation 4: every F_lmp starting at or below I^4, each through I^4.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l2_i4[9] = {
    {0, 2}, {2, 3}, {5, 2}, {7, 2}, {9, 2}, {11, 1},
    {12, 3}, {15, 2}, {17, 1},
};
inline constexpr double c_obliquity_coeffs_l2_i4[18] = {
    -0.375, 0.125, -0.5, 0.75, -0.25, -0.375,
    0.125, 1.5, -0.625, -1.5, 1.0, -0.375,
    3.0, -1.5, 0.3125, 1.5, -0.5, 0.1875,
};

// General: the half-angle sum of every F_lmp, exact at any obliquity.
inline constexpr c_ObliquityModeSeries c_obliquity_general_modes_l2[9] = {
    {0, 1}, {1, 3}, {4, 1}, {5, 1}, {6, 2}, {8, 1},
    {9, 1}, {10, 1}, {11, 1},
};
inline constexpr c_ObliquityHalfAngleTerm c_obliquity_general_terms_l2[12] = {
    {-1.5, 2, 2}, {-0.5, 4, 0}, {2.0, 2, 2},
    {-0.5, 0, 4}, {-1.5, 2, 2}, {3.0, 3, 1},
    {-3.0, 3, 1}, {3.0, 1, 3}, {-3.0, 1, 3},
    {3.0, 4, 0}, {6.0, 2, 2}, {3.0, 0, 4},
};

// The tables of one truncation level; a table with no modes for an untabulated level.
inline c_ObliquitySeriesTable c_obliquity_series_l2(int truncation) noexcept {
    switch (truncation) {
        case 0: return c_ObliquitySeriesTable{2, 0, c_obliquity_modes_l2_i0, c_obliquity_coeffs_l2_i0};
        case 2: return c_ObliquitySeriesTable{2, 2, c_obliquity_modes_l2_i2, c_obliquity_coeffs_l2_i2};
        case 4: return c_ObliquitySeriesTable{2, 4, c_obliquity_modes_l2_i4, c_obliquity_coeffs_l2_i4};
        default: return c_ObliquitySeriesTable{};
    }
}

// The half-angle table of the general truncation.
inline c_ObliquityGeneralTable c_obliquity_general_l2() noexcept {
    return c_ObliquityGeneralTable{2, c_obliquity_general_modes_l2, c_obliquity_general_terms_l2};
}
