#pragma once
/*
 * eccentricity_common_.hpp - the eccentricity-function table format and its evaluation.
 *
 * The eccentricity functions are Hansen coefficients, G_lpq(e) = X^{-(l+1), l-2p}_{l-2p+q}(e) (Kaula 1964). Truncation
 * level N (an even number) is defined by the heating: every product of two eccentricity functions is kept through e^N
 * and nothing past it. A level's table holds every mode with |q| <= N as its Taylor series through e^N,
 *
 *   G_lpq(e) = e^|q| * sum_j c_j e^(2j),   |q| + 2j <= N,
 *
 * so the unsquared functions, and a tidal potential built from them, are complete through e^N. Products are formed and
 * cut at e^N here (c_eccentricity_cut_product), which is why a mode enters the heating only when |q| <= N / 2. The
 * k = l - 2p + q = 0 modes are exact: (1 - e^2)^(1/2 - l) times a finite polynomial (Laskar and Boue 2010), and a
 * product of two of them is exact at every order.
 *
 * The tables (eccentricity_func_l{l}_.hpp) are generated by cpp_eccentricity_func_builder.py in the derivations
 * repository with exact rational arithmetic. Each is dense in (p, q): entry p * (2N + 1) + (q + N) is mode (p, q), and a
 * mode that vanishes identically, or whose series is zero through e^N (a zero leading coefficient at a low level), has no
 * coefficients.
 */

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <vector>

#include "../mode_func_common_.hpp"               // c_ModeFuncOutput
#include "../../Utilities_x/math_x/series_.hpp"   // Horner sums, powers, cut Cauchy products
#include "eccentricity_accuracy_.hpp"             // C_ECCENTRICITY_EXACT

// The tabulated truncation levels, the one list every entry point validates against.
inline constexpr int C_ECCENTRICITY_TRUNCATIONS[] = {2, 4, 6, 8, 10, 20, 50};
inline constexpr int C_NUM_ECCENTRICITY_TRUNCATIONS =
    static_cast<int>(sizeof(C_ECCENTRICITY_TRUNCATIONS) / sizeof(C_ECCENTRICITY_TRUNCATIONS[0]));

// One mode of a level's table: its coefficients c_j of e^(|q| + 2j) in the level's coefficient array.
struct c_EccentricityModeSeries {
    int32_t offset;   // index of c_0 in the level's coefficient array
    int16_t count;    // number of coefficients; 0 for a mode that vanishes identically or is zero through e^N
    int8_t  exact;    // 1 for a k = 0 closed form: the series times (1 - e^2)^(1/2 - l), exact at every order
};

// One (degree, truncation) table. modes is null for an untabulated level.
struct c_EccentricitySeriesTable {
    int degree_l = 0;
    int truncation = 0;
    const c_EccentricityModeSeries* modes = nullptr;
    const double* coefficients = nullptr;

    bool valid() const noexcept { return this->modes != nullptr; }

    // Mode (p, q) for 0 <= p <= l and |q| <= truncation.
    const c_EccentricityModeSeries& mode(int p, int q) const noexcept {
        return this->modes[p * (2 * this->truncation + 1) + (q + this->truncation)];
    }
};

// G_lpq of one degree, or its cut square, over 0 <= p <= l and |q| <= max_q; zero for every mode left out. table is the
// (degree, truncation) table the values came from, for the cut products of two of them, and invalid for the exact
// functions.
struct c_EccentricityValues {
    int degree_l = 0;
    int max_q = 0;
    std::vector<double> values;   // [p * (2 max_q + 1) + (q + max_q)]
    c_EccentricitySeriesTable table;

    double value(int p, int q) const noexcept {
        return this->values[static_cast<size_t>(p * (2 * this->max_q + 1) + (q + this->max_q))];
    }
};

// G_lpq(e) through e^N (exact for a k = 0 mode).
inline double c_eccentricity_mode_value(const c_EccentricitySeriesTable& table, int p, int q, double eccentricity)
        noexcept {
    const c_EccentricityModeSeries& mode = table.mode(p, q);
    if (mode.count == 0) { return 0.0; }
    const double e2 = eccentricity * eccentricity;
    double value = c_series_power(eccentricity, std::abs(q))
                 * c_series_horner(table.coefficients + mode.offset, mode.count, e2);
    if (mode.exact) {
        value *= std::pow(1.0 - e2, 0.5 - static_cast<double>(table.degree_l));
    }
    return value;
}

// The product G_a G_b cut at e^N, N the (common) truncation of the two tables. Zero when the product's leading power
// |q_a| + |q_b| is past e^N. Two exact (k = 0) factors give their exact product. One exact factor multiplies the other
// factor's series cut at e^(N - |q_exact|), so the product keeps every term through e^N that the series determine.
inline double c_eccentricity_cut_product(
        const c_EccentricitySeriesTable& table_a,
        int p_a,
        int q_a,
        const c_EccentricitySeriesTable& table_b,
        int p_b,
        int q_b,
        double eccentricity) noexcept {
    const int truncation = table_a.truncation;
    const int lead_a = std::abs(q_a);
    const int lead_b = std::abs(q_b);
    const int lead = lead_a + lead_b;
    if (lead > truncation) { return 0.0; }
    const c_EccentricityModeSeries& mode_a = table_a.mode(p_a, q_a);
    const c_EccentricityModeSeries& mode_b = table_b.mode(p_b, q_b);
    if ((mode_a.count == 0) || (mode_b.count == 0)) { return 0.0; }
    const double e2 = eccentricity * eccentricity;
    const double* coefficients_a = table_a.coefficients + mode_a.offset;
    const double* coefficients_b = table_b.coefficients + mode_b.offset;
    // Terms of e^(2s) past the leading power that stay within e^N.
    const int max_s = (truncation - lead) / 2;

    if (mode_a.exact && mode_b.exact) {
        return c_eccentricity_mode_value(table_a, p_a, q_a, eccentricity)
             * c_eccentricity_mode_value(table_b, p_b, q_b, eccentricity);
    }
    if (mode_a.exact || mode_b.exact) {
        const bool a_exact = mode_a.exact;
        const double exact_value = a_exact ? c_eccentricity_mode_value(table_a, p_a, q_a, eccentricity)
                                           : c_eccentricity_mode_value(table_b, p_b, q_b, eccentricity);
        const double* series = a_exact ? coefficients_b : coefficients_a;
        const int count = a_exact ? mode_b.count : mode_a.count;
        const int series_lead = a_exact ? lead_b : lead_a;
        const int num_terms = (count < max_s + 1) ? count : (max_s + 1);
        return exact_value * c_series_power(eccentricity, series_lead)
             * c_series_horner(series, num_terms, e2);
    }

    // Cauchy product of the two series, cut at e^(2 max_s) past the leading power, then Horner in e^2.
    const double total = c_series_cut_product(
        c_SeriesSpan{coefficients_a, mode_a.count}, c_SeriesSpan{coefficients_b, mode_b.count}, max_s, e2);
    return c_series_power(eccentricity, lead) * total;
}
