"""Material property laws: equations of state and shear-modulus laws, each a family of C++ models built by name."""

from TidalPy.Material.laws.laws import (
    EOSBase,
    ConstantEOS,
    BirchMurnaghanEOS,
    VinetEOS,
    MurnaghanEOS,
    PolytropeEOS,
    ModifiedPolytropeEOS,
    InterpolatedEOS,
    make_eos,
    eos_model_names,
    canonical_eos_name,
    eos_config_keys,
    ShearModulusBase,
    ConstantShearModulus,
    LinearShearModulus,
    InterpolatedShearModulus,
    make_shear_modulus,
    shear_modulus_model_names,
    canonical_shear_modulus_name,
    shear_modulus_config_keys,
)

__all__ = [
    "EOSBase",
    "ConstantEOS",
    "BirchMurnaghanEOS",
    "VinetEOS",
    "MurnaghanEOS",
    "PolytropeEOS",
    "ModifiedPolytropeEOS",
    "InterpolatedEOS",
    "make_eos",
    "eos_model_names",
    "canonical_eos_name",
    "eos_config_keys",
    "ShearModulusBase",
    "ConstantShearModulus",
    "LinearShearModulus",
    "InterpolatedShearModulus",
    "make_shear_modulus",
    "shear_modulus_model_names",
    "canonical_shear_modulus_name",
    "shear_modulus_config_keys",
]
