#pragma once
/*
 * legendre_l7_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 7, orders m = 0..7. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 7, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l7(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (429.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 693.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t) + (315.0/16.0)*(cos_t*cos_t*cos_t) - 35.0/16.0*cos_t,
            -3003.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (3465.0/16.0)*(cos_t*cos_t*cos_t*cos_t)*sin_t - 945.0/16.0*(cos_t*cos_t)*sin_t + (35.0/16.0)*sin_t,
            -3003.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (9009.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (3465.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t) - 3465.0/4.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 945.0/16.0*(cos_t*cos_t*cos_t) + (945.0/8.0)*cos_t*(sin_t*sin_t) + (35.0/16.0)*cos_t};
    case 1:
        return c_LegendreValue {
            -3003.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (3465.0/16.0)*(cos_t*cos_t*cos_t*cos_t)*sin_t - 945.0/16.0*(cos_t*cos_t)*sin_t + (35.0/16.0)*sin_t,
            -3003.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (9009.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (3465.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t) - 3465.0/4.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 945.0/16.0*(cos_t*cos_t*cos_t) + (945.0/8.0)*cos_t*(sin_t*sin_t) + (35.0/16.0)*cos_t,
            (57057.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 45045.0/8.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 45045.0/16.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (10395.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (6615.0/16.0)*(cos_t*cos_t)*sin_t - 945.0/8.0*(sin_t*sin_t*sin_t) - 35.0/16.0*sin_t};
    case 2:
        return c_LegendreValue {
            (9009.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3465.0/4.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (945.0/8.0)*cos_t*(sin_t*sin_t),
            (9009.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 45045.0/8.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 3465.0/2.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (10395.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (945.0/4.0)*(cos_t*cos_t)*sin_t - 945.0/8.0*(sin_t*sin_t*sin_t),
            (9009.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 243243.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3465.0/2.0*(cos_t*cos_t*cos_t*cos_t*cos_t) + (45045.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (58905.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (945.0/4.0)*(cos_t*cos_t*cos_t) - 10395.0/2.0*cos_t*(sin_t*sin_t*sin_t*sin_t) - 6615.0/8.0*cos_t*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -45045.0/8.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (10395.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 945.0/8.0*(sin_t*sin_t*sin_t),
            -135135.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (45045.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (31185.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 10395.0/2.0*cos_t*(sin_t*sin_t*sin_t*sin_t) - 2835.0/8.0*cos_t*(sin_t*sin_t),
            -135135.0/4.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (1396395.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (31185.0/2.0)*(cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 176715.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 2835.0/4.0*(cos_t*cos_t)*sin_t + (10395.0/2.0)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (2835.0/8.0)*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            (45045.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 10395.0/2.0*cos_t*(sin_t*sin_t*sin_t*sin_t),
            90090*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 135135.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 20790*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (10395.0/2.0)*(sin_t*sin_t*sin_t*sin_t*sin_t),
            270270*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 1396395.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 62370*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + 135135*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (135135.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t)};
    case 5:
        return c_LegendreValue {
            -135135.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (10395.0/2.0)*(sin_t*sin_t*sin_t*sin_t*sin_t),
            -675675.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + 135135*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (51975.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t),
            -1351350*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (3648645.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 103950*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 135135*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 51975.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 6:
        return c_LegendreValue {
            135135*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            810810*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 135135*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            4054050*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 2567565*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 7:
        return c_LegendreValue {
            -135135*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -945945*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -5675670*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 945945*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
