#pragma once
/*
 * legendre_l9_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 9, orders m = 0..9. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 9, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l9(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (12155.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 6435.0/32.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (9009.0/64.0)*(cos_t*cos_t*cos_t*cos_t*cos_t) - 1155.0/32.0*(cos_t*cos_t*cos_t) + (315.0/128.0)*cos_t,
            -109395.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (45045.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 45045.0/64.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (3465.0/32.0)*(cos_t*cos_t)*sin_t - 315.0/128.0*sin_t,
            -109395.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (109395.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (45045.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 135135.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 45045.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t) + (45045.0/16.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (3465.0/32.0)*(cos_t*cos_t*cos_t) - 3465.0/16.0*cos_t*(sin_t*sin_t) - 315.0/128.0*cos_t};
    case 1:
        return c_LegendreValue {
            -109395.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (45045.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 45045.0/64.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (3465.0/32.0)*(cos_t*cos_t)*sin_t - 315.0/128.0*sin_t,
            -109395.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (109395.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (45045.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 135135.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 45045.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t) + (45045.0/16.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (3465.0/32.0)*(cos_t*cos_t*cos_t) - 3465.0/16.0*cos_t*(sin_t*sin_t) - 315.0/128.0*cos_t,
            (2734875.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 765765.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 855855.0/32.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (675675.0/16.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (585585.0/64.0)*(cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/16.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 24255.0/32.0*(cos_t*cos_t)*sin_t + (3465.0/16.0)*(sin_t*sin_t*sin_t) + (315.0/128.0)*sin_t};
    case 2:
        return c_LegendreValue {
            (109395.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 135135.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (45045.0/16.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3465.0/16.0*cos_t*(sin_t*sin_t),
            (109395.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 765765.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 135135.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (675675.0/16.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (45045.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/16.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 3465.0/8.0*(cos_t*cos_t)*sin_t + (3465.0/16.0)*(sin_t*sin_t*sin_t),
            (109395.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 4047615.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 135135.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (2297295.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (3648645.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (45045.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t) - 675675.0/4.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 765765.0/16.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3465.0/8.0*(cos_t*cos_t*cos_t) + (135135.0/8.0)*cos_t*(sin_t*sin_t*sin_t*sin_t) + (24255.0/16.0)*cos_t*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -765765.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (675675.0/16.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 135135.0/16.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (3465.0/16.0)*(sin_t*sin_t*sin_t),
            -2297295.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (2297295.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (2027025.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 675675.0/4.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 405405.0/16.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (135135.0/8.0)*cos_t*(sin_t*sin_t*sin_t*sin_t) + (10395.0/16.0)*cos_t*(sin_t*sin_t),
            -2297295.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (34459425.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (2027025.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 11486475.0/8.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 20945925.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 405405.0/8.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (2027025.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (2297295.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (10395.0/8.0)*(cos_t*cos_t)*sin_t - 135135.0/8.0*(sin_t*sin_t*sin_t*sin_t*sin_t) - 10395.0/16.0*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            (2297295.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 675675.0/4.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (135135.0/8.0)*cos_t*(sin_t*sin_t*sin_t*sin_t),
            (2297295.0/2.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 11486475.0/8.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 675675*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (2027025.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (135135.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 135135.0/8.0*(sin_t*sin_t*sin_t*sin_t*sin_t),
            (6891885.0/2.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 112567455.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 2027025*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (11486475.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (20945925.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (405405.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 2027025.0/2.0*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 1756755.0/8.0*cos_t*(sin_t*sin_t*sin_t*sin_t)};
    case 5:
        return c_LegendreValue {
            -11486475.0/8.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (2027025.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 135135.0/8.0*(sin_t*sin_t*sin_t*sin_t*sin_t),
            -57432375.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (11486475.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (10135125.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 2027025.0/2.0*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 675675.0/8.0*cos_t*(sin_t*sin_t*sin_t*sin_t),
            -57432375.0/2.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (562837275.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 10135125*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 34459425.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 54729675.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 675675.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (2027025.0/2.0)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (675675.0/8.0)*(sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 6:
        return c_LegendreValue {
            (11486475.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 2027025.0/2.0*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            34459425*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 34459425.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 6081075*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (2027025.0/2.0)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            172297125*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 516891375.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 30405375*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + 34459425*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (38513475.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 7:
        return c_LegendreValue {
            -34459425.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (2027025.0/2.0)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -241215975.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 34459425*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (14189175.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -723647925*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (1274998725.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 42567525*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 34459425*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 14189175.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 8:
        return c_LegendreValue {
            34459425*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            275675400*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 34459425*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            1929727800*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 861485625*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 9:
        return c_LegendreValue {
            -34459425*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -310134825*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -2481078600*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 310134825*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
