#pragma once
/*
 * legendre_l8_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 8, orders m = 0..8. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 8, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l8(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (6435.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 3003.0/32.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (3465.0/64.0)*(cos_t*cos_t*cos_t*cos_t) - 315.0/32.0*(cos_t*cos_t) + 35.0/128.0,
            -6435.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (9009.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 3465.0/16.0*(cos_t*cos_t*cos_t)*sin_t + (315.0/16.0)*cos_t*sin_t,
            -6435.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (45045.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (9009.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 45045.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3465.0/16.0*(cos_t*cos_t*cos_t*cos_t) + (10395.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t) + (315.0/16.0)*(cos_t*cos_t) - 315.0/16.0*(sin_t*sin_t)};
    case 1:
        return c_LegendreValue {
            -6435.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (9009.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 3465.0/16.0*(cos_t*cos_t*cos_t)*sin_t + (315.0/16.0)*cos_t*sin_t,
            -6435.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (45045.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (9009.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 45045.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3465.0/16.0*(cos_t*cos_t*cos_t*cos_t) + (10395.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t) + (315.0/16.0)*(cos_t*cos_t) - 315.0/16.0*(sin_t*sin_t),
            (70785.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 9009*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (45045.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (17325.0/8.0)*(cos_t*cos_t*cos_t)*sin_t - 10395.0/8.0*cos_t*(sin_t*sin_t*sin_t) - 315.0/4.0*cos_t*sin_t};
    case 2:
        return c_LegendreValue {
            (45045.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 45045.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (10395.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t) - 315.0/16.0*(sin_t*sin_t),
            (45045.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 45045.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (45045.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (10395.0/8.0)*(cos_t*cos_t*cos_t)*sin_t - 10395.0/8.0*cos_t*(sin_t*sin_t*sin_t) - 315.0/8.0*cos_t*sin_t,
            (45045.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 90090*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 45045.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (675675.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (495495.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (10395.0/8.0)*(cos_t*cos_t*cos_t*cos_t) - 135135.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 31185.0/4.0*(cos_t*cos_t)*(sin_t*sin_t) - 315.0/8.0*(cos_t*cos_t) + (10395.0/8.0)*(sin_t*sin_t*sin_t*sin_t) + (315.0/8.0)*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -135135.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (45045.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 10395.0/8.0*cos_t*(sin_t*sin_t*sin_t),
            -405405.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (675675.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (135135.0/4.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 135135.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 31185.0/8.0*(cos_t*cos_t)*(sin_t*sin_t) + (10395.0/8.0)*(sin_t*sin_t*sin_t*sin_t),
            -405405.0/4.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (2567565.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (135135.0/2.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 675675.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 270270*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 31185.0/4.0*(cos_t*cos_t*cos_t)*sin_t + (135135.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t) + (51975.0/4.0)*cos_t*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            (675675.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 135135.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (10395.0/8.0)*(sin_t*sin_t*sin_t*sin_t),
            (675675.0/2.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 675675.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 135135*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (135135.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t) + (10395.0/2.0)*cos_t*(sin_t*sin_t*sin_t),
            (2027025.0/2.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 3378375*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 405405*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (2027025.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (1486485.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (31185.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t) - 135135.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 10395.0/2.0*(sin_t*sin_t*sin_t*sin_t)};
    case 5:
        return c_LegendreValue {
            -675675.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (135135.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t),
            -3378375.0/2.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (2027025.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (675675.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 135135.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -6756750*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + 12837825*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 1351350*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 2027025*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 1081080*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 6:
        return c_LegendreValue {
            (2027025.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 135135.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            6081075*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 2027025*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 405405*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t),
            30405375*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 32432400*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 2027025*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + 2027025*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 405405*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 7:
        return c_LegendreValue {
            -2027025*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -14189175*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 2027025*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -85135050*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 44594550*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 8:
        return c_LegendreValue {
            2027025*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            16216200*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            113513400*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 16216200*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
