#pragma once
/*
 * legendre_l3_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 3, orders m = 0..3. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 3, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l3(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (5.0/2.0)*(cos_t*cos_t*cos_t) - 3.0/2.0*cos_t,
            -15.0/2.0*(cos_t*cos_t)*sin_t + (3.0/2.0)*sin_t,
            -15.0/2.0*(cos_t*cos_t*cos_t) + 15*cos_t*(sin_t*sin_t) + (3.0/2.0)*cos_t};
    case 1:
        return c_LegendreValue {
            -15.0/2.0*(cos_t*cos_t)*sin_t + (3.0/2.0)*sin_t,
            -15.0/2.0*(cos_t*cos_t*cos_t) + 15*cos_t*(sin_t*sin_t) + (3.0/2.0)*cos_t,
            (105.0/2.0)*(cos_t*cos_t)*sin_t - 15*(sin_t*sin_t*sin_t) - 3.0/2.0*sin_t};
    case 2:
        return c_LegendreValue {
            15*cos_t*(sin_t*sin_t),
            30*(cos_t*cos_t)*sin_t - 15*(sin_t*sin_t*sin_t),
            30*(cos_t*cos_t*cos_t) - 105*cos_t*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -15*(sin_t*sin_t*sin_t),
            -45*cos_t*(sin_t*sin_t),
            -90*(cos_t*cos_t)*sin_t + 45*(sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
