#pragma once
/*
 * legendre_l10_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 10, orders m = 0..10. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 10, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l10(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (46189.0/256.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 109395.0/256.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (45045.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 15015.0/128.0*(cos_t*cos_t*cos_t*cos_t) + (3465.0/256.0)*(cos_t*cos_t) - 63.0/256.0,
            -230945.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (109395.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (15015.0/32.0)*(cos_t*cos_t*cos_t)*sin_t - 3465.0/128.0*cos_t*sin_t,
            -230945.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (2078505.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (109395.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 765765.0/32.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 135135.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (675675.0/64.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (15015.0/32.0)*(cos_t*cos_t*cos_t*cos_t) - 45045.0/32.0*(cos_t*cos_t)*(sin_t*sin_t) - 3465.0/128.0*(cos_t*cos_t) + (3465.0/128.0)*(sin_t*sin_t)};
    case 1:
        return c_LegendreValue {
            -230945.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (109395.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 135135.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (15015.0/32.0)*(cos_t*cos_t*cos_t)*sin_t - 3465.0/128.0*cos_t*sin_t,
            -230945.0/128.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (2078505.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (109395.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 765765.0/32.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 135135.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (675675.0/64.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (15015.0/32.0)*(cos_t*cos_t*cos_t*cos_t) - 45045.0/32.0*(cos_t*cos_t)*(sin_t*sin_t) - 3465.0/128.0*(cos_t*cos_t) + (3465.0/128.0)*(sin_t*sin_t),
            (1616615.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 2078505.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 1203345.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (2297295.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (135135.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 675675.0/16.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 75075.0/16.0*(cos_t*cos_t*cos_t)*sin_t + (45045.0/16.0)*cos_t*(sin_t*sin_t*sin_t) + (3465.0/32.0)*cos_t*sin_t};
    case 2:
        return c_LegendreValue {
            (2078505.0/128.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 765765.0/32.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (675675.0/64.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 45045.0/32.0*(cos_t*cos_t)*(sin_t*sin_t) + (3465.0/128.0)*(sin_t*sin_t),
            (2078505.0/64.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 2078505.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 765765.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (2297295.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (675675.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 675675.0/16.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 45045.0/16.0*(cos_t*cos_t*cos_t)*sin_t + (45045.0/16.0)*cos_t*(sin_t*sin_t*sin_t) + (3465.0/64.0)*cos_t*sin_t,
            (2078505.0/64.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 43648605.0/64.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 765765.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (14549535.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + 765765*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (675675.0/32.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 11486475.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 7432425.0/32.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 45045.0/16.0*(cos_t*cos_t*cos_t*cos_t) + (2027025.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (135135.0/8.0)*(cos_t*cos_t)*(sin_t*sin_t) + (3465.0/64.0)*(cos_t*cos_t) - 45045.0/16.0*(sin_t*sin_t*sin_t*sin_t) - 3465.0/64.0*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -2078505.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (2297295.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 675675.0/16.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (45045.0/16.0)*cos_t*(sin_t*sin_t*sin_t),
            -6235515.0/16.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (14549535.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (6891885.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 11486475.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 2027025.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (2027025.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (135135.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t) - 45045.0/16.0*(sin_t*sin_t*sin_t*sin_t),
            -6235515.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (27020565.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (6891885.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 43648605.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 43648605.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 2027025.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (11486475.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (2027025.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (135135.0/8.0)*(cos_t*cos_t*cos_t)*sin_t - 2027025.0/8.0*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t) - 225225.0/8.0*cos_t*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            (14549535.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 11486475.0/16.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (2027025.0/16.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 45045.0/16.0*(sin_t*sin_t*sin_t*sin_t),
            (14549535.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 43648605.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 11486475.0/4.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (11486475.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (2027025.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 2027025.0/8.0*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t) - 45045.0/4.0*cos_t*(sin_t*sin_t*sin_t),
            (43648605.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 421936515.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 34459425.0/4.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (218243025.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (57432375.0/2.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (6081075.0/4.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 34459425.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 22297275.0/8.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 135135.0/4.0*(cos_t*cos_t)*(sin_t*sin_t) + (2027025.0/8.0)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (45045.0/4.0)*(sin_t*sin_t*sin_t*sin_t)};
    case 5:
        return c_LegendreValue {
            -43648605.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (11486475.0/4.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 2027025.0/8.0*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t),
            -218243025.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (218243025.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (57432375.0/4.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 34459425.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 10135125.0/8.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (2027025.0/8.0)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -218243025.0/2.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (654729075.0/2.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 57432375*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 218243025.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 218243025.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 10135125.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (34459425.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 4054050*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 6:
        return c_LegendreValue {
            (218243025.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 34459425.0/4.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (2027025.0/8.0)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            (654729075.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 218243025.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 103378275.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + (34459425.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (6081075.0/4.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t),
            (3273645375.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 6329047725.0/4.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 516891375.0/2.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (654729075.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 275675400*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (30405375.0/4.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 34459425.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 6081075.0/4.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 7:
        return c_LegendreValue {
            -218243025.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (34459425.0/2.0)*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -1527701175.0/2.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (654729075.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + (241215975.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 34459425.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -4583103525*(cos_t*cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) + 5674318650*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 723647925*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t) - 654729075*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 379053675*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 8:
        return c_LegendreValue {
            (654729075.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 34459425.0/2.0*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            2618916300*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 654729075*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 137837700*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            18332414100*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 13749310575*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 964863900*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 654729075*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 137837700*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 9:
        return c_LegendreValue {
            -654729075*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -5892561675*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 654729075*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -47140493400*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 18332414100*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 10:
        return c_LegendreValue {
            654729075*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            6547290750*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            58925616750*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) - 6547290750*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
