#pragma once
/*
 * legendre_l4_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 4, orders m = 0..4. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 4, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l4(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (35.0/8.0)*(cos_t*cos_t*cos_t*cos_t) - 15.0/4.0*(cos_t*cos_t) + 3.0/8.0,
            -35.0/2.0*(cos_t*cos_t*cos_t)*sin_t + (15.0/2.0)*cos_t*sin_t,
            -35.0/2.0*(cos_t*cos_t*cos_t*cos_t) + (105.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t) + (15.0/2.0)*(cos_t*cos_t) - 15.0/2.0*(sin_t*sin_t)};
    case 1:
        return c_LegendreValue {
            -35.0/2.0*(cos_t*cos_t*cos_t)*sin_t + (15.0/2.0)*cos_t*sin_t,
            -35.0/2.0*(cos_t*cos_t*cos_t*cos_t) + (105.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t) + (15.0/2.0)*(cos_t*cos_t) - 15.0/2.0*(sin_t*sin_t),
            175*(cos_t*cos_t*cos_t)*sin_t - 105*cos_t*(sin_t*sin_t*sin_t) - 30*cos_t*sin_t};
    case 2:
        return c_LegendreValue {
            (105.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t) - 15.0/2.0*(sin_t*sin_t),
            105*(cos_t*cos_t*cos_t)*sin_t - 105*cos_t*(sin_t*sin_t*sin_t) - 15*cos_t*sin_t,
            105*(cos_t*cos_t*cos_t*cos_t) - 630*(cos_t*cos_t)*(sin_t*sin_t) - 15*(cos_t*cos_t) + 105*(sin_t*sin_t*sin_t*sin_t) + 15*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -105*cos_t*(sin_t*sin_t*sin_t),
            -315*(cos_t*cos_t)*(sin_t*sin_t) + 105*(sin_t*sin_t*sin_t*sin_t),
            -630*(cos_t*cos_t*cos_t)*sin_t + 1050*cos_t*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            105*(sin_t*sin_t*sin_t*sin_t),
            420*cos_t*(sin_t*sin_t*sin_t),
            1260*(cos_t*cos_t)*(sin_t*sin_t) - 420*(sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
