#pragma once
/*
 * legendre_l6_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 6, orders m = 0..6. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 6, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l6(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (231.0/16.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 315.0/16.0*(cos_t*cos_t*cos_t*cos_t) + (105.0/16.0)*(cos_t*cos_t) - 5.0/16.0,
            -693.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (315.0/4.0)*(cos_t*cos_t*cos_t)*sin_t - 105.0/8.0*cos_t*sin_t,
            -693.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (3465.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (315.0/4.0)*(cos_t*cos_t*cos_t*cos_t) - 945.0/4.0*(cos_t*cos_t)*(sin_t*sin_t) - 105.0/8.0*(cos_t*cos_t) + (105.0/8.0)*(sin_t*sin_t)};
    case 1:
        return c_LegendreValue {
            -693.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + (315.0/4.0)*(cos_t*cos_t*cos_t)*sin_t - 105.0/8.0*cos_t*sin_t,
            -693.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) + (3465.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (315.0/4.0)*(cos_t*cos_t*cos_t*cos_t) - 945.0/4.0*(cos_t*cos_t)*(sin_t*sin_t) - 105.0/8.0*(cos_t*cos_t) + (105.0/8.0)*(sin_t*sin_t),
            1386*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 3465.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 1575.0/2.0*(cos_t*cos_t*cos_t)*sin_t + (945.0/2.0)*cos_t*(sin_t*sin_t*sin_t) + (105.0/2.0)*cos_t*sin_t};
    case 2:
        return c_LegendreValue {
            (3465.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 945.0/4.0*(cos_t*cos_t)*(sin_t*sin_t) + (105.0/8.0)*(sin_t*sin_t),
            (3465.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t - 3465.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 945.0/2.0*(cos_t*cos_t*cos_t)*sin_t + (945.0/2.0)*cos_t*(sin_t*sin_t*sin_t) + (105.0/4.0)*cos_t*sin_t,
            (3465.0/4.0)*(cos_t*cos_t*cos_t*cos_t*cos_t*cos_t) - 38115.0/4.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 945.0/2.0*(cos_t*cos_t*cos_t*cos_t) + (10395.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + 2835*(cos_t*cos_t)*(sin_t*sin_t) + (105.0/4.0)*(cos_t*cos_t) - 945.0/2.0*(sin_t*sin_t*sin_t*sin_t) - 105.0/4.0*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -3465.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + (945.0/2.0)*cos_t*(sin_t*sin_t*sin_t),
            -10395.0/2.0*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) + (10395.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + (2835.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t) - 945.0/2.0*(sin_t*sin_t*sin_t*sin_t),
            -10395*(cos_t*cos_t*cos_t*cos_t*cos_t)*sin_t + 41580*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + 2835*(cos_t*cos_t*cos_t)*sin_t - 10395*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t) - 4725*cos_t*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            (10395.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 945.0/2.0*(sin_t*sin_t*sin_t*sin_t),
            20790*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) - 10395*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t) - 1890*cos_t*(sin_t*sin_t*sin_t),
            62370*(cos_t*cos_t*cos_t*cos_t)*(sin_t*sin_t) - 114345*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 5670*(cos_t*cos_t)*(sin_t*sin_t) + 10395*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t) + 1890*(sin_t*sin_t*sin_t*sin_t)};
    case 5:
        return c_LegendreValue {
            -10395*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t),
            -51975*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) + 10395*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            -207900*(cos_t*cos_t*cos_t)*(sin_t*sin_t*sin_t) + 166320*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t)};
    case 6:
        return c_LegendreValue {
            10395*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t),
            62370*cos_t*(sin_t*sin_t*sin_t*sin_t*sin_t),
            311850*(cos_t*cos_t)*(sin_t*sin_t*sin_t*sin_t) - 62370*(sin_t*sin_t*sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
