#pragma once
/*
 * legendre_l5_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 5, orders m = 0..5. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 5, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l5(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (63.0/8.0)*(cos_t*cos_t*cos_t*cos_t*cos_t) - 35.0/4.0*(cos_t*cos_t*cos_t) + (15.0/8.0)*cos_t,
            -315.0/8.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (105.0/4.0)*(cos_t*cos_t)*sin_t - 15.0/8.0*sin_t,
            -315.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t) + (315.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (105.0/4.0)*(cos_t*cos_t*cos_t) - 105.0/2.0*cos_t*(sin_t*sin_t) - 15.0/8.0*cos_t};
    case 1:
        return c_LegendreValue {
            -315.0/8.0*(cos_t*cos_t*cos_t*cos_t)*sin_t + (105.0/4.0)*(cos_t*cos_t)*sin_t - 15.0/8.0*sin_t,
            -315.0/8.0*(cos_t*cos_t*cos_t*cos_t*cos_t) + (315.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + (105.0/4.0)*(cos_t*cos_t*cos_t) - 105.0/2.0*cos_t*(sin_t*sin_t) - 15.0/8.0*cos_t,
            (4095.0/8.0)*(cos_t*cos_t*cos_t*cos_t)*sin_t - 945.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 735.0/4.0*(cos_t*cos_t)*sin_t + (105.0/2.0)*(sin_t*sin_t*sin_t) + (15.0/8.0)*sin_t};
    case 2:
        return c_LegendreValue {
            (315.0/2.0)*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 105.0/2.0*cos_t*(sin_t*sin_t),
            315*(cos_t*cos_t*cos_t*cos_t)*sin_t - 945.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 105*(cos_t*cos_t)*sin_t + (105.0/2.0)*(sin_t*sin_t*sin_t),
            315*(cos_t*cos_t*cos_t*cos_t*cos_t) - 5355.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 105*(cos_t*cos_t*cos_t) + 945*cos_t*(sin_t*sin_t*sin_t*sin_t) + (735.0/2.0)*cos_t*(sin_t*sin_t)};
    case 3:
        return c_LegendreValue {
            -945.0/2.0*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + (105.0/2.0)*(sin_t*sin_t*sin_t),
            -2835.0/2.0*(cos_t*cos_t*cos_t)*(sin_t*sin_t) + 945*cos_t*(sin_t*sin_t*sin_t*sin_t) + (315.0/2.0)*cos_t*(sin_t*sin_t),
            -2835*(cos_t*cos_t*cos_t*cos_t)*sin_t + (16065.0/2.0)*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + 315*(cos_t*cos_t)*sin_t - 945*(sin_t*sin_t*sin_t*sin_t*sin_t) - 315.0/2.0*(sin_t*sin_t*sin_t)};
    case 4:
        return c_LegendreValue {
            945*cos_t*(sin_t*sin_t*sin_t*sin_t),
            3780*(cos_t*cos_t)*(sin_t*sin_t*sin_t) - 945*(sin_t*sin_t*sin_t*sin_t*sin_t),
            11340*(cos_t*cos_t*cos_t)*(sin_t*sin_t) - 12285*cos_t*(sin_t*sin_t*sin_t*sin_t)};
    case 5:
        return c_LegendreValue {
            -945*(sin_t*sin_t*sin_t*sin_t*sin_t),
            -4725*cos_t*(sin_t*sin_t*sin_t*sin_t),
            -18900*(cos_t*cos_t)*(sin_t*sin_t*sin_t) + 4725*(sin_t*sin_t*sin_t*sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
