#pragma once
/*
 * legendre_l2_.hpp - Precomputed associated Legendre functions P_lm(cos theta) and their first and
 * second colatitude derivatives for degree l = 2, orders m = 0..2. Generated by
 * scratchpad/gen_legendre.py (Ferrers form, Condon-Shortley phase; matches sympy.assoc_legendre).
 * Do not edit by hand; regenerate instead. All angles in radians; colatitude theta in [0, pi].
 */

#include <cstdint>

#include "legendre_common_.hpp"

namespace tidalpy {

// Associated Legendre triple for degree l = 2, order m, given cos_t = cos(theta), sin_t = sin(theta).
inline c_LegendreValue c_legendre_l2(int order_m, double cos_t, double sin_t)
{
    switch (order_m)
    {
    case 0:
        return c_LegendreValue {
            (3.0/2.0)*(cos_t*cos_t) - 1.0/2.0,
            -3*cos_t*sin_t,
            -3*(cos_t*cos_t) + 3*(sin_t*sin_t)};
    case 1:
        return c_LegendreValue {
            -3*cos_t*sin_t,
            -3*(cos_t*cos_t) + 3*(sin_t*sin_t),
            12*cos_t*sin_t};
    case 2:
        return c_LegendreValue {
            3*(sin_t*sin_t),
            6*cos_t*sin_t,
            6*(cos_t*cos_t) - 6*(sin_t*sin_t)};

    default:
        return c_LegendreValue {TidalPyConstants::d_NAN, TidalPyConstants::d_NAN, TidalPyConstants::d_NAN};
    }
}

} // namespace tidalpy
