# Very roughly pulled from some analysis by Dorn+ (A&A 2017)

name = "55-Cancri-e"
type = "burnman"
radius = 11950000.0
semi_major_axis = 0.01544
semi_major_axis_in_au = true
eccentricity = 0.02
spin_period = 1.0
force_spin_sync = true

[layers.Core]
type = "iron"
is_tidal = false
radius = 4000000.0
material = "Fe_Dewaele"
material_source = "other"
temperature_mode = "user-defined"
temperature_fixed = 300.0

[layers.Lower_Mantle]
type = "rock"
is_tidal = false
radius = 8959000.0
material = "mg_bridgmanite"
material_source = "SLB_2011"
temperature_mode = "adiabatic"

[layers.Upper_Mantle]
type = "rock"
is_tidal = true
radius = 11950000.0
material = "forsterite"
material_source = "SLB_2011"
temperature_mode = "adiabatic"
temperature_top = 1200.0
surface_temperature = 300.0
