# Very roughly pulled from some analysis by Dorn+ (A&A 2017)

name = "55-Cancri-e"
type = "layered"
radius = 11950000.0
semi_major_axis = 0.01544
semi_major_axis_in_au = true
eccentricity = 0.02
spin_period = 1.0
force_spin_sync = true

[layers.Core]
type = "iron"
is_tidal = false
radius = 4000000.0
density = 14000.0

[layers.Lower_Mantle]
type = "rock"
is_tidal = false
radius = 8959000.0
density = 5000.0

[layers.Upper_Mantle]
type = "rock"
is_tidal = true
radius = 11950000.0
density = 3300.0
