# Radius: Delrez et al., (2018) corrected by Kane et al., (2018)
# Masses: Grimm et al., (2018)
# Gravity: g*mass/(R2)
# Flux: Delrez et al., (2018) corrected by Kane et al., (2018)
# Density (Jontof-Hutter et al., 2014): radii: Delrez et al., (2018) + masses: Grimm e al (2018) corrected by Kane et al., (2018)
# Updated using the analysis done by Agol+2020 and references therein.

name = "TRAPPIST-1f"
type = "simple_tidal"
radius = 6664000.0
radius_error_pos = 85000.0
radius_error_neg = 77000.0
mass = 6.205e+24
mass_error_pos = 1.84e+23
mass_error_neg = 1.84e+23
semi_major_axis = 5758000000.0
semi_major_axis_error_pos = 49000000.0
semi_major_axis_error_neg = 49000000.0
semi_major_axis_in_au = false
eccentricity = 0.004455
eccentricity_error_pos = 0.003945
eccentricity_error_neg = 0.003945
force_spin_sync = true
