#pragma once
// Obliquity-function tables for degree l = 3, generated by
// cpp_obliquity_func_builder.py (derivations repository). Do not edit by hand.

#include "obliquity_common_.hpp"

// Truncation 0: every F_lmp starting at or below I^0, each through I^0.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l3_i0[16] = {
    {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 1},
    {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0},
    {1, 1}, {2, 0}, {2, 0}, {2, 0},
};
inline constexpr double c_obliquity_coeffs_l3_i0[2] = {
    -1.5, 15.0,
};

// Truncation 2: every F_lmp starting at or below I^2, each through I^2.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l3_i2[16] = {
    {0, 0}, {0, 1}, {1, 1}, {2, 0}, {2, 1}, {3, 2},
    {5, 1}, {6, 0}, {6, 1}, {7, 1}, {8, 0}, {8, 0},
    {8, 2}, {10, 1}, {11, 0}, {11, 0},
};
inline constexpr double c_obliquity_coeffs_l3_i2[11] = {
    -0.75, 0.75, -1.875, -1.5, 4.125, -2.25,
    7.5, -7.5, 15.0, -11.25, 11.25,
};

// Truncation 4: every F_lmp starting at or below I^4, each through I^4.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l3_i4[16] = {
    {0, 1}, {1, 2}, {3, 2}, {5, 1}, {6, 2}, {8, 3},
    {11, 2}, {13, 1}, {14, 2}, {16, 2}, {18, 1}, {19, 0},
    {19, 3}, {22, 2}, {24, 1}, {25, 0},
};
inline constexpr double c_obliquity_coeffs_l3_i4[25] = {
    -0.3125, -0.75, 1.0625, 0.75, -1.0625, 0.3125,
    -1.875, 1.09375, -1.5, 4.125, -2.6875, -2.25,
    2.0625, -0.46875, 7.5, -5.0, -7.5, 8.75,
    -3.75, 15.0, -11.25, 3.75, 11.25, -6.5625,
    2.8125,
};

// General: the half-angle sum of every F_lmp, exact at any obliquity.
inline constexpr c_ObliquityModeSeries c_obliquity_general_modes_l3[16] = {
    {0, 1}, {1, 3}, {4, 3}, {7, 1}, {8, 1}, {9, 3},
    {12, 3}, {15, 1}, {16, 1}, {17, 2}, {19, 2}, {21, 1},
    {22, 1}, {23, 1}, {24, 1}, {25, 1},
};
inline constexpr c_ObliquityHalfAngleTerm c_obliquity_general_terms_l3[26] = {
    {-2.5, 3, 3}, {-1.5, 5, 1}, {4.5, 3, 3},
    {-1.5, 1, 5}, {1.5, 5, 1}, {-4.5, 3, 3},
    {1.5, 1, 5}, {2.5, 3, 3}, {-7.5, 4, 2},
    {-1.5, 6, 0}, {12.0, 4, 2}, {-9.0, 2, 4},
    {-9.0, 4, 2}, {12.0, 2, 4}, {-1.5, 0, 6},
    {-7.5, 2, 4}, {15.0, 5, 1}, {-15.0, 5, 1},
    {30.0, 3, 3}, {-30.0, 3, 3}, {15.0, 1, 5},
    {-15.0, 1, 5}, {15.0, 6, 0}, {45.0, 4, 2},
    {45.0, 2, 4}, {15.0, 0, 6},
};

// The tables of one truncation level; a table with no modes for an untabulated level.
inline c_ObliquitySeriesTable c_obliquity_series_l3(int truncation) noexcept {
    switch (truncation) {
        case 0: return c_ObliquitySeriesTable{3, 0, c_obliquity_modes_l3_i0, c_obliquity_coeffs_l3_i0};
        case 2: return c_ObliquitySeriesTable{3, 2, c_obliquity_modes_l3_i2, c_obliquity_coeffs_l3_i2};
        case 4: return c_ObliquitySeriesTable{3, 4, c_obliquity_modes_l3_i4, c_obliquity_coeffs_l3_i4};
        default: return c_ObliquitySeriesTable{};
    }
}

// The half-angle table of the general truncation.
inline c_ObliquityGeneralTable c_obliquity_general_l3() noexcept {
    return c_ObliquityGeneralTable{3, c_obliquity_general_modes_l3, c_obliquity_general_terms_l3};
}
