#pragma once
// Obliquity-function tables for degree l = 4, generated by
// cpp_obliquity_func_builder.py (derivations repository). Do not edit by hand.

#include "obliquity_common_.hpp"

// Truncation 0: every F_lmp starting at or below I^0, each through I^0.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l4_i0[25] = {
    {0, 0}, {0, 0}, {0, 1}, {1, 0}, {1, 0}, {1, 0},
    {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 0}, {1, 1},
    {2, 0}, {2, 0}, {2, 0}, {2, 0}, {2, 0}, {2, 0},
    {2, 0}, {2, 0}, {2, 1}, {3, 0}, {3, 0}, {3, 0},
    {3, 0},
};
inline constexpr double c_obliquity_coeffs_l4_i0[3] = {
    0.375, -7.5, 105.0,
};

// Truncation 2: every F_lmp starting at or below I^2, each through I^2.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l4_i2[25] = {
    {0, 0}, {0, 1}, {1, 2}, {3, 1}, {4, 0}, {4, 0},
    {4, 1}, {5, 1}, {6, 0}, {6, 0}, {6, 1}, {7, 2},
    {9, 1}, {10, 0}, {10, 0}, {10, 1}, {11, 1}, {12, 0},
    {12, 0}, {12, 0}, {12, 2}, {14, 1}, {15, 0}, {15, 0},
    {15, 0},
};
inline constexpr double c_obliquity_coeffs_l4_i2[15] = {
    0.9375, 0.375, -1.875, 0.9375, -3.75, 3.75,
    -13.125, -7.5, 30.0, -16.875, 52.5, -52.5,
    105.0, -105.0, 105.0,
};

// Truncation 4: every F_lmp starting at or below I^4, each through I^4.
inline constexpr c_ObliquityModeSeries c_obliquity_modes_l4_i4[25] = {
    {0, 1}, {1, 2}, {3, 3}, {6, 2}, {8, 1}, {9, 1},
    {10, 2}, {12, 2}, {14, 1}, {15, 0}, {15, 2}, {17, 3},
    {20, 2}, {22, 1}, {23, 0}, {23, 2}, {25, 2}, {27, 1},
    {28, 0}, {28, 0}, {28, 3}, {31, 2}, {33, 1}, {34, 0},
    {34, 0},
};
inline constexpr double c_obliquity_coeffs_l4_i4[34] = {
    0.2734375, 0.9375, -1.40625, 0.375, -1.875, 2.265625,
    0.9375, -1.40625, 0.2734375, -2.1875, -3.75, 8.125,
    3.75, -9.0625, 3.125, -13.125, 10.9375, -7.5,
    30.0, -29.21875, -16.875, 25.3125, -7.03125, 52.5,
    -48.125, -52.5, 87.5, -39.375, 105.0, -105.0,
    48.125, 105.0, -87.5, 39.375,
};

// General: the half-angle sum of every F_lmp, exact at any obliquity.
inline constexpr c_ObliquityModeSeries c_obliquity_general_modes_l4[25] = {
    {0, 1}, {1, 3}, {4, 5}, {9, 3}, {12, 1}, {13, 1},
    {14, 3}, {17, 4}, {21, 3}, {24, 1}, {25, 1}, {26, 3},
    {29, 3}, {32, 3}, {35, 1}, {36, 1}, {37, 2}, {39, 2},
    {41, 2}, {43, 1}, {44, 1}, {45, 1}, {46, 1}, {47, 1},
    {48, 1},
};
inline constexpr c_ObliquityHalfAngleTerm c_obliquity_general_terms_l4[49] = {
    {4.375, 4, 4}, {3.75, 6, 2}, {-10.0, 4, 4},
    {3.75, 2, 6}, {0.375, 8, 0}, {-6.0, 6, 2},
    {13.5, 4, 4}, {-6.0, 2, 6}, {0.375, 0, 8},
    {3.75, 6, 2}, {-10.0, 4, 4}, {3.75, 2, 6},
    {4.375, 4, 4}, {-17.5, 5, 3}, {-7.5, 7, 1},
    {37.5, 5, 3}, {-25.0, 3, 5}, {7.5, 7, 1},
    {-45.0, 5, 3}, {45.0, 3, 5}, {-7.5, 1, 7},
    {25.0, 5, 3}, {-37.5, 3, 5}, {7.5, 1, 7},
    {17.5, 3, 5}, {-52.5, 6, 2}, {-7.5, 8, 0},
    {90.0, 6, 2}, {-112.5, 4, 4}, {-67.5, 6, 2},
    {180.0, 4, 4}, {-67.5, 2, 6}, {-112.5, 4, 4},
    {90.0, 2, 6}, {-7.5, 0, 8}, {-52.5, 2, 6},
    {105.0, 7, 1}, {-105.0, 7, 1}, {315.0, 5, 3},
    {-315.0, 5, 3}, {315.0, 3, 5}, {-315.0, 3, 5},
    {105.0, 1, 7}, {-105.0, 1, 7}, {105.0, 8, 0},
    {420.0, 6, 2}, {630.0, 4, 4}, {420.0, 2, 6},
    {105.0, 0, 8},
};

// The tables of one truncation level; a table with no modes for an untabulated level.
inline c_ObliquitySeriesTable c_obliquity_series_l4(int truncation) noexcept {
    switch (truncation) {
        case 0: return c_ObliquitySeriesTable{4, 0, c_obliquity_modes_l4_i0, c_obliquity_coeffs_l4_i0};
        case 2: return c_ObliquitySeriesTable{4, 2, c_obliquity_modes_l4_i2, c_obliquity_coeffs_l4_i2};
        case 4: return c_ObliquitySeriesTable{4, 4, c_obliquity_modes_l4_i4, c_obliquity_coeffs_l4_i4};
        default: return c_ObliquitySeriesTable{};
    }
}

// The half-angle table of the general truncation.
inline c_ObliquityGeneralTable c_obliquity_general_l4() noexcept {
    return c_ObliquityGeneralTable{4, c_obliquity_general_modes_l4, c_obliquity_general_terms_l4};
}
