name: Build Wheels for Test PyPI

on:
  workflow_dispatch:

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz

  build_wheels:
    name: Build ${{ matrix.platform }} wheels
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
          platform:
              - macos-12
              - windows-2022
              - ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  check_dist:
    name: Check dist
    needs: [make_sdist, build_wheels]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - run: pipx run twine check --strict dist/*

  upload_all:
    name: Upload wheels to Test PyPI
    needs: [build_wheels, make_sdist, check_dist]
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/